### PR TITLE
Replace all ASCII signs in NameNormalizer::normalize

### PR DESCRIPTION
**Pull request by szepeviktor**
```bash
for C in {32..126}; do printf "\\x$(printf "%x" $C)"; done|sed -e 's#[0-9A-Z_a-z]##g'
```

### CODE REVIEW

**Comment by szepeviktor** [comment]
❌ some of these new replacements are not Unicode character codes but literal characters making ICU crazy
```
  #>\u005f;                                                                    
  %>\u005f;                                                                    
  &>\u005f;                                                                    
  +>\u005f;                                                                    
  @>\u005f;                                                                    
  >\u005f;                                                                    
  `>\u005f;                                                                    
```

**Comment by PrinsFrank** [comment]
> ❌ some of these new replacement rules are not Unicode characters codes but literal characters making ICU crazy
> 
> ```
>   #>\u005f;                                                                    
>   %>\u005f;                                                                    
>   &>\u005f;                                                                    
>   +>\u005f;                                                                    
>   @>\u005f;                                                                    
>   >\u005f;                                                                    
>   `>\u005f;                                                                    
> ```

You can add them in this enum, which will result in those chars being escaped when a transliterator is built: https://github.com/PrinsFrank/transliteration/blob/main/src/Enum/Literal.php

**Comment by szepeviktor** [comment]
> You can add them in this enum, which will result in those chars being escaped when a transliterator is built: https://github.com/PrinsFrank/transliteration/blob/main/src/Enum/Literal.php

Where should I get their names?
From Unicode? https://unicode.org/charts/PDF/U0000.pdf

**Comment by PrinsFrank** [comment]
@szepeviktor FYI: I clicked the 'Update Branch' button on this PR as the transliteration package fix has been released and is now used in main. ;)

**Comment by PrinsFrank** [comment]
Thanks!

**Pull request merged**
