### PR TITLE
Add TravelDocuments Alpha2/Alpha3 UserAssigned country codes in new specfication

### PR DESCRIPTION
**Pull request by rbiya**

### CODE REVIEW

**Comment by PrinsFrank** [comment]
Fixes #95

**Review by PrinsFrank — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution!

The alpha3 codes that are added here, are not universal but are in the "User-assigned code" space, as defined in the [glossary for ISO-3166](https://www.iso.org/glossary-for-iso-3166.html): 

>User-assigned codes - If users need code elements to represent country names not included in ISO 3166-1, the series of letters AA, QM to QZ, XA to XZ, and ZZ, and the series AAA to AAZ, QMA to QZZ, XAA to XZZ, and ZZA to ZZZ respectively, and the series of numbers 900 to 999 are available.
NOTE: Please be advised that the above series of codes are not universal, those code elements are not compatible between different entities.

Different standards might add different definitions for the same values. Can you instead add a new enum in `src/country/UserAssigned/MachineReadablePassportsAlpha3.php` with these cases? And can you also add all the items that are not in the ISO-3166 spec to that? A list can be found in the specification document here: https://www.icao.int/publications/Documents/9303_p3_cons_en.pdf on page 29 (Chapter 5 part A-F). There are also some Alpha2 codes, If you have time you could also add that?

If you change this, the new syntax for retrieving the countryCode or MachineReadableCode will become:
```php
$alpha3 = CountryAlpha3::tryfrom($string) ?? MachineReadableCodeAlpha3::tryFrom($string) ?? null;
``

**Comment by PrinsFrank** [comment]
Thanks again for your contribution! I hope the current implementation fits your need! Normally I wouldn't do this, but I've processed the feedback as I'll be on holiday later today. This way you can use the changes sooner instead of waiting for me to come back. Please comment on this PR if I've missed anything!

**Review by PrinsFrank — APPROVED** [review]

**Comment by szepeviktor** [comment]
> as I'll be on holiday later today.

✈️ I gave Frank free tickets to `case Utopia`.

**Pull request merged**
