### PR TITLE
Improve CurrencyMapping

### PR DESCRIPTION
**Pull request by szepeviktor**
Make country names readable.

GitHub even glitches out from the long line.
Try scrolling horizontally!

### CODE REVIEW

**Comment by szepeviktor** [comment]
@PrinsFrank Seem like SIX Group banned GitHub IP-s: it times out.
https://github.com/PrinsFrank/standards/actions/workflows/update-spec-currency.yml

**Comment by szepeviktor** [comment]
```
Error: Curl error thrown for http POST to /session/7b1ae433-5cc0-4531-8c46-9bde9c8f0294/url
```

What could this request be??

**Comment by andrew-demb** [comment]
@szepeviktor tried to investigate a bit - this is internals from web driver library - how it communicates with the browser from PHP

Refs:
- https://github.com/php-webdriver/php-webdriver/issues/1048
- https://github.com/mozilla/geckodriver/issues/2082
- https://github.com/php-webdriver/php-webdriver/blob/4c18b78d93e4a724ad2dd6427ed658e61a45c569/lib/Remote/HttpCommandExecutor.php#L43

**Review by PrinsFrank — APPROVED** [review]
Thank you!!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
