### PR TITLE
Debug SIX Group connection

### PR DESCRIPTION
**Pull request by szepeviktor**
`curl -vvv` 🔎

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is no problem :(
`HTTP/1.1 200 OK`

**Comment by andrew-demb** [comment]
@szepeviktor tried to investigate a bit - this is internals from web driver library - how it communicates with the browser from PHP (error from Gthub action from https://github.com/PrinsFrank/standards/pull/255#issuecomment-2408748729)

Refs:
- https://github.com/php-webdriver/php-webdriver/issues/1048
- https://github.com/mozilla/geckodriver/issues/2082
- https://github.com/php-webdriver/php-webdriver/blob/4c18b78d93e4a724ad2dd6427ed658e61a45c569/lib/Remote/HttpCommandExecutor.php#L43

**Comment by PrinsFrank** [comment]
I've looked at several environment variables. I've looked at the installed packages on the last succesfull run compared to the first failing one and those are identical. I suspect the local browser drivers in github actions have gotten a new version, which don't handle XML files correctly as their first request. At least that's my suspicion right now. I'll dive into this a bit deeper once I have some more time over the next few days.

**Comment by szepeviktor** [comment]
All right.

**Pull request closed without merging**
