### PR TITLE
Add supported scripts for PHP regexes

### PR DESCRIPTION
**Pull request by PrinsFrank**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Oh nooooooooooooooooooooooooooooooo!

**Comment by szepeviktor** [comment]
Scripts are not born but are dying out ...

This is a massive overkill.

**Comment by PrinsFrank** [comment]
@szepeviktor Most of the changes in this PR are bugfixes for updating the same file multiple times, which causes issues because PHP doesn't reload classes and as a result weird things were happening, so don't be overwhelmed by the size of this PR.

My intention with this package is to move more things to attributes. Adding an attribute per supported script and a method to check for the existence of that attribute is not overkill, right? Or did you have a more elegant solution in mind?

**Comment by szepeviktor** [comment]
Sorry. The **updater** is the overkill.

**Comment by PrinsFrank** [comment]
> Sorry. The **updater** is the overkill.

Ah, cool. And yeah, agreed. The fun thing is that I went into this thinking: I don't want to add an attribute manually for each script that is supported by PHP regexes, it's probably faster to do it with mapping. But then I ran into all kind of weird edge cases like PHP not liking that I update classes in the background etc. So Eventually it took more time.

**Pull request merged**
