### PR TITLE
Fix enum method generation issues with docblocks

### PR DESCRIPTION
**Pull request by PrinsFrank**

### CODE REVIEW

**Comment by PrinsFrank** [comment]
🐇🐇🐇

**Comment by szepeviktor** [comment]
Countries crawling has an intermittent problem.
https://github.com/PrinsFrank/standards/actions/runs/9782516706/job/27009008635?pr=241
Seen on main branch too.

**Comment by PrinsFrank** [comment]
Yeah, I saw that too. I am currently trying to figure out how to have multibyte support for PREG_OFFSET_CAPTURE. PHP is nice, but I think I have something figured out. Will push some changes shortly.

**Comment by szepeviktor** [comment]
You could temporarily convert to UTF-32 and divide positions by 4.
https://stackoverflow.com/a/3432593

**Pull request merged**
