### PR TITLE
Add lek to 4217

### PR DESCRIPTION
**Pull request by szepeviktor**
Data source: https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list_one.xml

### CODE REVIEW

**Review by PrinsFrank — CHANGES_REQUESTED** [review]
Hey @szepeviktor, the ```Albanian_Lek``` backed enum got renamed to ```Lek```to follow the spec mentioned in your comment. It is also regenerated daily from source, as you can see in #15. It is weird that the branch is not failing on a duplicate backed value, 008 is already present.

**Comment by szepeviktor** [comment]
> It is weird that the branch is not failing on a duplicate backed value

It is up to you to investigate.

**Comment by PrinsFrank** [comment]
@szepeviktor I'm getting PHPStan up and running for this project, which wil detect duplicate backing values. This PR can then be closed in favor of #17 right?

**Comment by szepeviktor** [comment]
Let's see that warning!!

**Pull request closed without merging**
