### PR TITLE
Fiddle with uniqueness in EnumCase

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://github.com/PrinsFrank/standards/pull/183#issuecomment-1918910818

### CODE REVIEW

**Comment by szepeviktor** [comment]
@PrinsFrank This seem impossible to solve!
```diff
     case eu = 'eu';
+    case eu = 'ею';
+    case eu = 'ευ';
```
What to do?? eu2, eu3 ... ?

**Comment by szepeviktor** [comment]
> detecting what script the initial text was

The only thing I can think of is looping through all `ScriptCode`-s and try matching `^\p{sc=Hira}+$`
https://www.unicode.org/reports/tr18/#Script_Property

**Comment by PrinsFrank** [comment]
@szepeviktor That's quite smart actually! If that is reliable it would be cool to add that the the transliteration package!

**Comment by szepeviktor** [comment]
all non-Latin
```
alardn seems to be a Arabic
albhryn seems to be a Arabic
aljzayr seems to be a Arabic
almghrb seems to be a Arabic
alswdyt seems to be a Arabic
amarat seems to be a Arabic
ao_men seems to be a Han
art seems to be a Arabic
ayran seems to be a Arabic
banla seems to be a Bengali
bart seems to be a Arabic
bel seems to be a Cyrillic
bharat seems to be a Telugu
bharata seems to be a Kannada
bharatam seems to be a Devanagari
bharota seems to be a Devanagari
cinkappur seems to be a Tamil
el seems to be a Greek
flstyn seems to be a Arabic
hangug seems to be a Hangul
hay seems to be a Armenian
ilankai seems to be a Tamil
intiya seems to be a Tamil
kaz seems to be a Cyrillic
laav seems to be a Lao
lanka seems to be a Sinhala
man seems to be a Arabic
mkd seems to be a Cyrillic
mlysya seems to be a Arabic
mon seems to be a Cyrillic
msr seems to be a Arabic
mwrytanya seems to be a Arabic
pakstan seems to be a Arabic
qtr seems to be a Arabic
raq seems to be a Arabic
rf seems to be a Cyrillic
srb seems to be a Cyrillic
swdan seems to be a Arabic
swryt seems to be a Arabic
tai_wan seems to be a Han
thiy seems to be a Thai
twns seems to be a Arabic
ukr seems to be a Cyrillic
xiang_gang seems to be a Han
xin_jia_po seems to be a Han
ysr_l seems to be a Hebrew
zhong_guo seems to be a Han
```

**Comment by szepeviktor** [comment]
PHP supports these scripts: https://www.php.net/manual/en/regexp.reference.unicode.php
not all our `ScriptCode`-s

```php
    foreach ($scripts as $script) {
        if (preg_match('/^\p{' . $script . '}+$/u', $string) === 1) {
            return $script;
        }
    }
    return '?';
```
Please write the actual code.

**Comment by szepeviktor** [comment]
I'm searching for the _where_ but EnumCase does not know about other cases and EnumFile cannot change the name in EnumCase (because it is readonly).

**Comment by szepeviktor** [comment]
I think we should never drop a duplicated value but throw an exception.
I hope there is no data source that contains duplicate rows!

Let's see whether there are TWO `eu_greek`-s.

**Comment by PrinsFrank** [comment]
fixed in #200. Thanks!

**Pull request closed without merging**
